### ISSUE TITLE
实现OCR算法

### ISSUE THREAD

**Issue by CCRcmcpe** [CCRcmcpe/Auto-Arknights#26]
方案|注释
-|-
Tesseract|训练过于麻烦
百度OCR|需要用户自行申请API Key，提供较多试用次数，精准度较低
腾讯OCR|需要用户自行申请API Key，提供的试用次数很少，但是精准度较高
自行实现|使用MSE/SSIM/CCOEFF匹配

**Comment by CCRcmcpe** [comment]
经查，是腾讯服务器垃圾导致。现在可以继续正常使用。

**Comment by CCRcmcpe** [comment]
经过进一步的检查，最近腾讯似乎有意限制了试用API的调用，所以OCR问题仍待解决。

**Comment by duzhaokun123** [comment]
参考 https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 参考 https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper

关于方案，其实这个也有考虑过，最终没有采用的原因是

- tesseract和Windows10自带OCR的识别准确率貌似不是很高
- 百度OCR API注册比较繁琐

不排除未来使用的可能性

**Comment by duzhaokun123** [comment]
> 参考 https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper

这个刷单关卡的 OCR 是用 OpenCV 自己实现的,

**Comment by CCRcmcpe** [comment]
目前开发者并没有足够的时间（和技术力）解决这个问题，等待进一步更新。

**Comment by CCRcmcpe** [comment]
#58

**Comment by CCRcmcpe** [comment]
https://github.com/CCRcmcpe/Auto-Arknights/commit/08a6917ebd57230acbe0ee329067344dbba1d7fd
